openapi: 3.0.0
info:
  version: "1.0"
  title: CoreHR API
  description: >
    # Introduction

    A collection of CoreHR APIs
        
    # Available authentication methods

 
tags:
  - name: Employees
    description: A collection of endpoints for employee
 
x-tagGroups:
  - name: Employees
    tags:
      - Get Employees
  
paths:
  /v1/tunnels:
    get:
      tags:
        - Tunnels
      summary: List All Tunnels
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tunnel"
              examples:
                response:
                  value:
                    - id: b3237483-e96e-4f3a-905c-0d9603d66c1f
                      created_at: 1534409264
                      updated_at: 1534409264
                      name: tunnel-x
                      destination: http://localhost:4000
                      host: tunnelx.webrelay.io
    post:
      tags:
        - Tunnels
      description: You may create your own tunnel using this action. It takes a JSON object
        containing a tunnel request with a specified destination. Paid plans
        have an option to specify either encryption, subdomain or full domain.
      summary: Create a New Tunnel
      requestBody:
        $ref: "#/components/requestBodies/Tunnel"
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tunnel"
              examples:
                response:
                  value:
                    id: b3237483-e96e-4f3a-905c-0d9603d66c1f
                    created_at: 1534409264
                    updated_at: 1534409264
                    name: tunnel-x
                    destination: http://localhost:4000
                    host: tunnelx.webrelay.io
            description:
              examples:
                response:
                  value: Create a tunnel with a custom subdomain
        "400":
          description: Invalid tunnel request supplied
    summary: List and create tunnels
  "/v1/tunnels/{tunnelID}":
    parameters:
      - name: tunnelID
        in: path
        description: ID of tunnel to return
        required: true
        schema:
          type: string
    get:
      tags:
        - Tunnels
      summary: Get Tunnel Details
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tunnel"
              examples:
                response:
                  value:
                    created_at: 1534409264
                    updated_at: 1534409264
                    id: b3237483-e96e-4f3a-905c-0d9603d66c1f
                    destination: http://localhost:8090
                    name: tunnel
                    group: ""
                    addr: ""
                    host: tunnelx.webrelay.io
                    mode: active
                    protocol: http
                    account_id: bd7e1dfc-54c8-408c-a885-7498bf1d8522
                    description: ""
                    features: null
                    auth:
                      created_at: 1534409264
                      updated_at: 1534409264
                      id: eb3fbc49-0713-48b1-8971-a7c4a9c64dfb
                      type: none
                    agent_id: ""
                    ingress_rules: null
                    crypto: off
        "404":
          description: Tunnel not found
    put:
      tags:
        - Tunnels
      summary: Update Tunnel Details
      requestBody:
        $ref: "#/components/requestBodies/Tunnel"
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tunnel"
              examples:
                response:
                  value:
                    created_at: 1534409264
                    updated_at: 1534409264
                    id: b3237483-e96e-4f3a-905c-0d9603d66c1f
                    destination: http://localhost:8090
                    name: tunnel
                    group: ""
                    addr: ""
                    host: tunnelx.webrelay.io
                    mode: active
                    protocol: http
                    account_id: bd7e1dfc-54c8-408c-a885-7498bf1d8522
                    description: ""
                    features: null
                    auth:
                      created_at: 1534409264
                      updated_at: 1534409264
                      id: eb3fbc49-0713-48b1-8971-a7c4a9c64dfb
                      type: none
                    agent_id: ""
                    ingress_rules: null
                    crypto: off
        "400":
          description: Bad request (check response message)
        "404":
          description: Tunnel not found
    delete:
      tags:
        - Tunnels
      summary: Delete Tunnel
      responses:
        "200":
          description: Successful Response
        "404":
          description: Tunnel not found
    summary: Get, update and delete tunnels
  
